import { navbar } from "vuepress-theme-hope";

export default navbar([
  { text: "首页", icon: "home", link: "/" },
  { text: "快速开始", icon: "rocket", link: "/guide/02-subscribe-plus.md" },
  { text: "学习路线", icon: "map", link: "/guide/00-overview.md" },
  { text: "入口地图", icon: "layout", link: "/platform/" },
  {
    text: "配置",
    icon: "gear",
    children: [
      { text: "配置总览", icon: "map", link: "/configuration/" },
      { text: "CLI 选项与命令", icon: "terminal", link: "/configuration/cli-options.md" },
      { text: "config.toml", icon: "config", link: "/configuration/config-file.md" },
      { text: "MCP、Skills 与 Subagents", icon: "plugin", link: "/configuration/mcp-skills-subagents.md" },
      { text: "安全与审批", icon: "safe", link: "/configuration/security-admin.md" },
    ],
  },
  {
    text: "资源",
    icon: "box",
    children: [
      { text: "实践方法", icon: "tool", link: "/practice/" },
      { text: "官方资料", icon: "link", link: "/reference/" },
      { text: "共建路线图", icon: "people", link: "/community/roadmap.md" },
    ],
  },
  {
    text: "教程",
    icon: "book",
    children: [
      { text: "01 Codex 桌面 App 下载与安装", icon: "desktop", link: "/guide/01-app-installation.md" },
      { text: "02 接入瞩目AI 中转 API", icon: "key", link: "/guide/02-subscribe-plus.md" },
      { text: "03 了解 Codex 桌面 App", icon: "layout", link: "/guide/03-app-overview.md" },
      { text: "04 手机端协同桌面任务", icon: "mobile", link: "/guide/04-mobile-control-desktop.md" },
      { text: "05 用 Codex 完成第一个任务", icon: "code", link: "/guide/05-app-first-task.md" },
      { text: "06 任务顺序执行与并行", icon: "list", link: "/guide/06-task-execution.md" },
      { text: "07 权限管理", icon: "safe", link: "/guide/07-permissions.md" },
      { text: "08 技能与插件", icon: "plugin", link: "/guide/08-skills-plugins.md" },
      { text: "09 自动化", icon: "time", link: "/guide/09-automation.md" },
      { text: "10 桌面宠物", icon: "cat", link: "/guide/10-desktop-pet.md" },
      { text: "11 CLI 安装与登录", icon: "download", link: "/guide/11-cli-installation.md" },
      { text: "12 第一次让 Codex 改代码", icon: "edit", link: "/guide/12-cli-first-run.md" },
      { text: "13 在 VS Code 中使用 Codex", icon: "code", link: "/guide/13-ide-vscode.md" },
      { text: "14 AGENTS.md", icon: "file", link: "/guide/14-agents-md.md" },
      { text: "15 沙盒与审批", icon: "lock", link: "/guide/15-sandbox-approvals.md" },
      { text: "16 Codex Cloud：使用云端模式", icon: "cloud", link: "/guide/16-cloud-ide-app.md" },
      { text: "17 排障手册", icon: "debug", link: "/guide/17-troubleshooting.md" },
    ],
  },
  {
    text: "实战案例",
    icon: "lightbulb",
    children: [
      { text: "案例总览", icon: "layout", link: "/recipes/" },
      { text: "01 Codex × PPT Skill：一句话生成演示文稿", icon: "slides", link: "/recipes/ppt-skill-walkthrough.md" },
      { text: "02 Codex × Draw.io MCP：AI 自动绘制架构图", icon: "diagram", link: "/recipes/drawio-mcp.md" },
      { text: "03 Codex × Playwright MCP：让 AI 操控浏览器", icon: "chrome", link: "/recipes/playwright-mcp.md" },
      { text: "04 Codex × HyperFrames：用代码生成动画视频", icon: "video", link: "/recipes/hyperframes-animation.md" },
      { text: "05 Codex × Obsidian：在知识库中自动生成配图", icon: "edit", link: "/recipes/obsidian-codex.md" },
      { text: "06 Codex × 飞书 CLI：一句话处理飞书数据", icon: "message", link: "/recipes/feishu-cli-codex.md" },
      { text: "07 Codex × LLM Wiki：在 Obsidian 中搭建 AI 知识库", icon: "note", link: "/recipes/llm-wiki-codex.md" },
      { text: "08 Codex × Figma MCP：读懂设计稿", icon: "palette", link: "/recipes/figma-mcp-codex.md" },
      { text: "09 Codex × Notion MCP：打通知识空间", icon: "note", link: "/recipes/notion-mcp-codex.md" },
      { text: "10 Codex × DKFile：网页一键发布到公网", icon: "launch", link: "/recipes/dkfile-deploy-codex.md" },
      { text: "11 Codex × 云服务器：远程定位并修复 Bug", icon: "server", link: "/recipes/remote-bug-fix.md" },
      { text: "12 Codex × Chrome：让 AI 直接控制浏览器", icon: "chrome", link: "/recipes/chrome-browser-plugin.md" },
      { text: "13 Codex × GitHub Actions：CI 失败自动修复", icon: "actions", link: "/recipes/github-actions-ci-fix.md" },
      { text: "参考来源与致谢", icon: "heart", link: "/recipes/credits.md" },
    ],
  },
]);
